### ISSUE TITLE
When totalCount is 0 (zero), causes UI problem

### ISSUE THREAD

**Issue by shinsou** [faulknercs/Knockstrap#57] opened 2017-04-26 19:04 UTC
Hi,

Couldn't find any similar posts. (Apologies if one did exist tho')

I noticed that if [totalCount] is 0, your logic here breaks:

```javascript
self.isForwardDisabled = ko.computed(function () {
    return self.currentPage() === self.pagesCount(); 
    // <-- problem, if pagesCount() == 0; where it is, if [totalCount] == 0
    //return self.currentPage() >= self.pagesCount(); <-- solved, or should I put logic to check if [totalCount] is zero, then change [currentPage] to zero?
});
```
and possible here:
```javascript
self.isBackDisabled = ko.computed(function () {
    return self.currentPage() === 1; 
});
```
It allows to use [Next] and [Last] -buttons, causing the page numbering to become negative based.
You can test this on your example (http://faulknercs.github.io/Knockstrap/#pagination) - just change [Total items] to 0 (zero) and press [Last] -button.

**Comment by faulknercs** [comment] 2017-07-14 15:19
Duplicate of #46

**Closed by faulknercs** 2017-07-14 15:19 UTC
Labels: duplicate
